# Script created by prof. Sibylle Vonesch

# Load packages

library(pacman)
pacman::p_load(ggplot2, DESeq2, readxl, IHW, data.table,
               tidyverse, viridis, ashr, BiocParallel, stats)

setwd("C:/...")

### function to get sgRNA level results
get_sgRNA_results <- function(dds, coef){
  resp <- results(dds, name = coef, alpha = 0.05, lfcThreshold = 0, altHypothesis = "greater")
  resdfp <- data.frame(resp)
  resdfp$sgRNA <- rownames(resdfp)
  resn <- results(dds, name = coef, alpha = 0.05, lfcThreshold = 0, altHypothesis = "less")
  resdfn <- data.frame(resn)[ , c("pvalue", "padj")]
  resdfn$sgRNA <- rownames(resdfn)
  colnames(resdfn) <- c("pvalue_neg", "padj_neg", "sgRNA")
  resdf <- merge(resdfp, resdfn, by = "sgRNA")
  resdf$coef <- coef
  resLFC <- lfcShrink(dds, coef = coef, type = "apeglm")
  lfc <- data.frame(lfc_MAP = resLFC$log2FoldChange)
  lfc$sgRNA <- rownames(resLFC)
  m_res <- merge(resdf, lfc, by = "sgRNA")
}

# EXPONENTIAL PHASE, DESeq2 -----------------------------------------------

# Load raw read count data

Raw_read_counts <- read_excel("SupplementaryData3_CRISPRi.xlsx", sheet = "RawCounts")
numeric <- as.tibble(apply(Raw_read_counts[, -1], 2, as.numeric))
Raw_read_counts <- bind_cols(Raw_read_counts[,1], numeric)
Raw_read_counts[is.na(Raw_read_counts)] <- 0 #Replace all NA values that the custom R script generated by 0.
Raw_read_counts <- Raw_read_counts[ , c(1:17)]

# Put data into matrix format for analysis

cts <- as.matrix(Raw_read_counts[ ,2:ncol(Raw_read_counts)])
rownames(cts) <- Raw_read_counts$sgRNA


# Generate a data frame containing the column/sample information

sid <- colnames(cts) #sid = sample ID
s <- strsplit(sid, "_")
strain <- unlist(lapply(s, "[[", 2))
inducer <- unlist(lapply(s, "[[", 3))
rep <- unlist(lapply(s, "[[", 4))
col_info <- data.frame(sid = sid, strain = strain, num_rep = rep,
                       inducer = inducer, stringsAsFactors = F)
all(colnames(cts)==col_info$sid) # This should return "TRUE"


# Make a DESeq2 dataset, factorize and set factor levels

dds <- DESeqDataSetFromMatrix(countData = cts, 
                              colData = col_info, design = ~1)

dds$strain <- factor(dds$strain, levels = c("Vector", "ObgE"))
dds$inducer <- factor(dds$inducer, levels = c("NoaTc", "aTc"))

levels(dds$strain)
levels(dds$inducer)


# DE analysis to compare between the Treated and the Untreated condition with Wald test

design(dds) <- formula(~ strain + inducer + strain:inducer)
model.matrix(design(dds), colData(dds))
dds <- DESeq(dds)

plotDispEsts(dds) #To check the dispersion

resultsNames(dds) #To see all the comparisons that can be made


## To get the results for the interaction term ((ObgE(+aTc vs -aTc) vs Vector(+aTc vs -aTc)) at the sgRNA level
rdf <- get_sgRNA_results(dds, "strainObgE.induceraTc")
write.table(rdf, "ExpPhase_ObgEvsVector.txt", row.names = F, quote = F, sep = "\t")


## To get the results for the Vector control (+aTc vs -aTc) at the sgRNA level
rdf <- get_sgRNA_results(dds, "inducer_aTc_vs_NoaTc")
write.table(rdf, "ExpPhase_Vector_aTcvsNoaTc.txt", row.names = F, quote = F, sep = "\t")

# STATIONARY PHASE, DESeq2 ------------------------------------------------


# Load raw read count data

Raw_read_counts <- read_excel("SupplementaryData3_CRISPRi.xlsx", sheet = "RawCounts")
numeric <- as.tibble(apply(Raw_read_counts[, -1], 2, as.numeric))
Raw_read_counts <- bind_cols(Raw_read_counts[,1], numeric)
Raw_read_counts[is.na(Raw_read_counts)] <- 0 #Replace all NA values that the custom R script generated by 0.
Raw_read_counts <- Raw_read_counts[ , c(1, 18:33)]

# Put data into matrix format for analysis

cts <- as.matrix(Raw_read_counts[ ,2:ncol(Raw_read_counts)])
rownames(cts) <- Raw_read_counts$sgRNA


# Generate a data frame containing the column/sample information

sid <- colnames(cts) #sid = sample ID
s <- strsplit(sid, "_")
strain <- unlist(lapply(s, "[[", 2))
inducer <- unlist(lapply(s, "[[", 3))
rep <- unlist(lapply(s, "[[", 4))
col_info <- data.frame(sid = sid, strain = strain, num_rep = rep,
                       inducer = inducer, stringsAsFactors = F)
all(colnames(cts)==col_info$sid) # This should return "TRUE"


# Make a DESeq2 dataset, factorize and set factor levels

dds <- DESeqDataSetFromMatrix(countData = cts, 
                              colData = col_info, design = ~1)

dds$strain <- factor(dds$strain, levels = c("Vector", "ObgE"))
dds$inducer <- factor(dds$inducer, levels = c("NoaTc", "aTc"))

levels(dds$strain)
levels(dds$inducer)


# DE analysis to compare between the Treated and the Untreated condition with Wald test

design(dds) <- formula(~ strain + inducer + strain:inducer)
model.matrix(design(dds), colData(dds))
dds <- DESeq(dds)

plotDispEsts(dds) #To check the dispersion

resultsNames(dds) #To see all the comparisons that can be made


## To get the results for the interaction term ((ObgE(+aTc vs -aTc) vs Vector(+aTc vs -aTc)) at the sgRNA level
rdf <- get_sgRNA_results(dds, "strainObgE.induceraTc")
write.table(rdf, "StatPhase_ObgEvsVector.txt", row.names = F, quote = F, sep = "\t")

###vector control induced vs noninduced
rdf <- get_sgRNA_results(dds, "inducer_aTc_vs_NoaTc")
write.table(rdf, "StatPhase_Vector_aTcvsNoaTc.txt", row.names = F, quote = F, sep = "\t")

# Functions for RRA analysis at the gene level ----------------------------

alphaBeta <- function (p_test) 
{
  p_test <- sort(p_test)
  n <- length(p_test)
  min(stats::pbeta(p_test, seq_len(n), n - seq_len(n) + 1))
}

makeRhoNull <- function (n, p, nperm) 
{
  alphaBeta <- function (p_test) 
  {
    p_test <- sort(p_test)
    n <- length(p_test)
    min(stats::pbeta(p_test, seq_len(n), n - seq_len(n) + 1))
  }
  n_processes <- 4
  rhonull <- BiocParallel::bplapply(seq_len(n_processes), function(x) {
    vapply(seq_len(nperm/n_processes), function(x) {
      alphaBeta(sample(p, n, replace = FALSE))
    }, FUN.VALUE = numeric(1))
  })
  unlist(rhonull)
}

get_gene_pvals <- function(df, direction){
  if(direction %in% "pos"){
    pvals <- df$padj
  }
  else if(direction %in% "neg"){
    pvals <- df$padj_neg
  }
  pvals[is.na(pvals)] <- as.numeric(1)
  genes <- df$gene
  perm_genes <- 8
  cut.pvals <- pvals <= 0.05
  score_vals <- rank(pvals)/length(pvals)
  score_vals[!cut.pvals] <- as.numeric(1)
  rho <- unsplit(vapply(split(score_vals, genes), FUN = alphaBeta, 
                        FUN.VALUE = numeric(1)), genes)
  guides_per_gene <- sort(unique(table(genes)))
  permutations <- perm_genes * length(unique(genes))
  rho_nullh <- vapply(guides_per_gene, FUN = makeRhoNull, p = score_vals, 
                      nperm = permutations, FUN.VALUE = numeric(permutations))
  
  pvalue_gene <- vapply(split(rho, genes), function(x) {
    n_sgrnas = length(x)
    mean(rho_nullh[, guides_per_gene == n_sgrnas] <= x[[1]])
  }, FUN.VALUE = numeric(1))
  
  pvalue_gene
}

#calculate gene-level fold change using sgRNA fold changes
fx_mean <- function(x, dir){
  if(dir == "pos"){
    tmp <- grep("T", x$padj < 0.05)
  }
  else if(dir == "neg"){
    tmp <- grep("T", x$padj_neg < 0.05)
  }
  if(length(tmp) > 0){
    ngrna <- length(tmp)
    lfc <- mean(x$lfc_MAP[tmp])
    d <- data.frame(ngrna = ngrna, gene_fc = lfc)
    return(d)
  }
  else if(length(tmp) == 0){
    d <- data.frame(ngrna = 0, gene_fc = 0)
    return(d)
  }
}
fx_median <- function(x, dir){
  if(dir == "pos"){
    tmp <- grep("T", x$padj < 0.05)
  }
  else if(dir == "neg"){
    tmp <- grep("T", x$padj_neg < 0.05)
  }
  if(length(tmp) > 0){
    ngrna <- length(tmp)
    lfc <- median(x$lfc_MAP[tmp])
    d <- data.frame(ngrna = ngrna, gene_fc = lfc)
    return(d)
  }
  else if(length(tmp) == 0){
    d <- data.frame(ngrna = 0, gene_fc = 0)
    return(d)
  }
}

get_gene_lfcs <- function (df, method, dir){

  if(method == "mean"){
    #uses mean FC of all sgRNAs for that gene
    vapply(split(df$lfc_MAP, df$gene), FUN = mean, FUN.VALUE = numeric(1))
  }
  else if(method == "median"){
    #uses median FC of all sgRNAs for that gene
    vapply(split(df$lfc_MAP, df$gene), FUN = median, FUN.VALUE = numeric(1))
  }
  else if(method == "alphamedian"){
    #uses median FC of all significant sgRNAs for that gene
    if(dir == "pos"){
      rbindlist(lapply(split(df, df$gene), FUN = fx_median, dir = dir))
    }
    if(dir == "neg"){
      rbindlist(lapply(split(df, df$gene), FUN = fx_median, dir = dir))
    }
    
  }
  else if(method == "alphamean"){
    #uses mean FC of all significant sgRNAs for that gene
    if(dir == "pos"){
      r <- rbindlist(lapply(split(df, df$gene), FUN = fx_mean, dir = dir))
      colnames(r) <- c("ngrna_lfc_pos", "gene_lfc_pos") #if error, remove l from lfc
      return(r)
    }
    else if(dir == "neg"){
      r <- rbindlist(lapply(split(df, df$gene), FUN = fx_mean, dir = dir))
      colnames(r) <- c("ngrna_lfc_neg", "gene_lfc_neg") #if error, remove l from lfc
      return(r)
    }
    return(r)
  }
}




# EXPONENTIAL PHASE, GENE LEVEL -------------------------------------------

resfiles <- c(dir(pattern = "^ExpPhase_"))
for(i in seq_along(resfiles)){
  df <- read.delim(resfiles[i])
  df$gene <- paste0(substr(df$sgRNA, 1, 4))
  df$gene <- sub('[b]$', '', df$gene, ignore.case = FALSE)
  dfl <- split(df, f = df$contrast)
  resl <- list()
  for(j in seq_along(dfl)){
    genepval_p <- get_gene_pvals(dfl[[j]], direction = "pos")
    fdr_gene_pos <- stats::p.adjust(genepval_p, method = "fdr")
    genepval_n <- get_gene_pvals(dfl[[j]], direction = "neg")
    fdr_gene_neg <- stats::p.adjust(genepval_n, method = "fdr")
    gene_lfc_pos <- get_gene_lfcs(dfl[[j]], method = "alphamean", dir = "pos")
    gene_lfc_neg <- get_gene_lfcs(dfl[[j]], method = "alphamean", dir = "neg")
    df2 <- data.frame(gene = names(genepval_p), gene_pval_pos = genepval_p, fdr_gene_pos = fdr_gene_pos,
                      gene_pval_neg = genepval_n, fdr_gene_neg = fdr_gene_neg,
                      gene_lfc_pos, gene_lfc_neg, contrast = unique(dfl[[j]]$contrast), stringsAsFactors = F)
    resl[[j]] <- df2
  }
  r <- rbindlist(resl)
  r$test <- gsub(".txt", "", resfiles[i])
  savepath <- paste0("gene_pvals_", resfiles[i])
  write.table(r, savepath, row.names = F, quote = F, sep = "\t")
}



# STATIONARY PHASE, GENE LEVEL --------------------------------------------

resfiles <- c(dir(pattern = "^StatPhase_"))
for(i in seq_along(resfiles)){
  df <- read.delim(resfiles[i])
  df$gene <- paste0(substr(df$sgRNA, 1, 4))
  df$gene <- sub('[b]$', '', df$gene, ignore.case = FALSE)
  dfl <- split(df, f = df$contrast)
  resl <- list()
  for(j in seq_along(dfl)){
    genepval_p <- get_gene_pvals(dfl[[j]], direction = "pos")
    fdr_gene_pos <- stats::p.adjust(genepval_p, method = "fdr")
    genepval_n <- get_gene_pvals(dfl[[j]], direction = "neg")
    fdr_gene_neg <- stats::p.adjust(genepval_n, method = "fdr")
    gene_lfc_pos <- get_gene_lfcs(dfl[[j]], method = "alphamean", dir = "pos")
    gene_lfc_neg <- get_gene_lfcs(dfl[[j]], method = "alphamean", dir = "neg")
    df2 <- data.frame(gene = names(genepval_p), gene_pval_pos = genepval_p, fdr_gene_pos = fdr_gene_pos,
                      gene_pval_neg = genepval_n, fdr_gene_neg = fdr_gene_neg,
                      gene_lfc_pos, gene_lfc_neg, contrast = unique(dfl[[j]]$contrast), stringsAsFactors = F)
    resl[[j]] <- df2
  }
  r <- rbindlist(resl)
  r$test <- gsub(".txt", "", resfiles[i])
  savepath <- paste0("gene_pvals_", resfiles[i])
  write.table(r, savepath, row.names = F, quote = F, sep = "\t")
}



